### ISSUE TITLE
Colisionador del héroe Feature??

### ISSUE THREAD

**Issue by Fernandolv123** [BraisGlezArias/TheHeroNeverDies#14]
El colisionador del héroe sigue activo mientras este esta muerto, lo que provoca que puedas empujar su cuerpo inerte

Esto podría ser un bug pero me ha parecido una mecánica interesante ya que puedes empujarlo a la esquina lo que lo crea estrategia
![imagen](https://github.com/BraisGlezArias/TheHeroNeverDies/assets/98803514/68604024-3898-49ad-8f62-5f0833c86cb4)

**Comment by BraisGlezArias** [comment]
La razón principal de mantenerlo fue debido a que el grounded tal y cómo lo tengo en el código no funciona sin el colisionador. Cambiarlo ahora mismo supone cierto esfuerzo y teniendo en cuenta que da cierta jugabilidad por el momento creo que lo mantendré. Issue cerrada.
