### ISSUE TITLE
Opiniones

### ISSUE THREAD

**Issue by Fernandolv123** [BraisGlezArias/TheHeroNeverDies#16]
Despues de jugar el juego durante aproximadamente unos 40 minutos, me parece un juego muy entretenido para jugar mientras estas esperando por gente o simplemente tienes unos minutillos tontos, la mecanica de las rondas siempre te hace querer mejorar y, en general resulta adictivo querer superar tu record una y otra vez (SOBRETODO SIN BUGS), parece una tontería pero el simple hecho de que tu primera habilidad tenga el rango justo para atacar sin que el te llegue le da al juego mucha variedad en cuanto a técnicas.

Me gustaría verte intentar un nuevo modo de juego con varias habilidades y/o efectos de estado, buen trabajo ^^ 8/10

**Comment by BraisGlezArias** [comment]
Gracias Fernando por dedicarle tanto tiempo al juego. Sobre todo me quedo con tus bonitas palabras y el saber que te ha resultado divertido me hace especialmente feliz. En cuánto a tus sugerencias, tengo ideas en mente para implementar, pero no puedo prometer nada por el momento.
