### ISSUE TITLE
Respuestas Diego

### ISSUE THREAD

**Issue by diegoAG100** [BraisGlezArias/TheHeroNeverDies#17]
1 Si es divertido, para que fuera mas divertido pondria mas poderes
2 Lo jugue 5 veces, el juego es repetitivo
3 Si que experimente errores de colisiones, creo que hay veces que por las formas del collider
4 No me aporta nada
5 Seria interesante un modo en el que fueses el héroe o uno en el que asciendas de nivel

**Comment by BraisGlezArias** [comment]
Gracias por tus respuestas honestas Diego, las valoro mucho y las tendré en cuenta de cara a mejoras en el juego. Un saludo.
