### ISSUE TITLE
Tipografía poco legible 

### ISSUE THREAD

**Issue by diegoAG100** [BraisGlezArias/TheHeroNeverDies#22]
La tipografía del juego cuesta de leer, yo creo que cambiarlo estaría bien

**Comment by kevincerro-dvrv** [comment]
Me ha pasado lo mismo, parece como que está muy estirada
![image](https://github.com/BraisGlezArias/TheHeroNeverDies/assets/148996189/6c986cc8-3bce-4be0-9e36-0e41ed966cc8)

**Comment by BraisGlezArias** [comment]
El problema está siendo tratado en https://github.com/BraisGlezArias/TheHeroNeverDies/issues/11

Gracias por su feedback.

Cierro issue.
