### ISSUE TITLE
Missing some keyboard guide

### ISSUE THREAD

**Issue by kevincerro-dvrv** [BraisGlezArias/TheHeroNeverDies#23]
When you start game, player can feel lost.

For example, how you can skip dialogues? (Press enter to skip)
![image](https://github.com/BraisGlezArias/TheHeroNeverDies/assets/148996189/af376132-610c-4ec9-b4b3-8c9aa47c42c4)

**Comment by BraisGlezArias** [comment]
This is being acknowledged at https://github.com/BraisGlezArias/TheHeroNeverDies/issues/21

Thank you for your feedback.

Closing issue.
