### ISSUE TITLE
Dead bodies can be pushed

### ISSUE THREAD

**Issue by kevincerro-dvrv** [BraisGlezArias/TheHeroNeverDies#25]
![image](https://github.com/BraisGlezArias/TheHeroNeverDies/assets/148996189/66f51463-143f-4631-9516-21af31d8efe6)

**Comment by BraisGlezArias** [comment]
Issue already answered at https://github.com/BraisGlezArias/TheHeroNeverDies/issues/14

Thank you for your feedback.
