### ISSUE TITLE
Jumping on edge takes player out of map

### ISSUE THREAD

**Issue by kevincerro-dvrv** [BraisGlezArias/TheHeroNeverDies#26]
Steps to reproduce
1. Go to reight edge
2. Spam jump key (space)
3. Keep right pressed
4. Player is out of map

![image](https://github.com/BraisGlezArias/TheHeroNeverDies/assets/148996189/2b43331f-157b-49a9-a2c5-b5e08a8faf96)

**Comment by BraisGlezArias** [comment]
This bug is being studied at https://github.com/BraisGlezArias/TheHeroNeverDies/issues/12

Thank you for your feedback.

Closing issue.
